
FROM node:lts-alpine as builder
WORKDIR /build
COPY package.json .
COPY package-lock.json .

RUN apk update && apk add gettext

RUN npm ci
COPY . .

RUN npm run build
FROM nginxinc/nginx-unprivileged:alpine
COPY ./nginx/http_prod.conf /etc/nginx/conf.d/default.conf

WORKDIR /app


COPY --from=builder /build/dist /app
